import json

# id -> (title, [tags])
ENTRIES = {
    "cs-001": ("#044 — Disconnected analytics is a losing deck", ["dashboards", "reporting"]),
    "cs-002": ("#045 — Shadow metrics tell the truth", ["vanity-metrics", "diagnostics"]),
    "cs-003": ("#048 — Don't measure everything. Navigate.", ["data-culture", "frameworks"]),
    "cs-004": ("#050 — From bestsellers to dead stock", ["ecommerce-metrics", "segmentation"]),
    "cs-005": ("#051 — Add to Cart Rate Driver Tree", ["metric-maps", "ecommerce-metrics"]),
    "cs-006": ("#052 — Same CR, different funnel", ["diagnostics", "ecommerce-metrics"]),
    "cs-007": ("#053 — LTV by segments is hidden gold", ["ecommerce-metrics", "segmentation"]),
    "cs-008": ("#054 — E-commerce Metrics Health Check", ["ecommerce-metrics", "frameworks"]),
    "cs-009": ("#055 — Fundamental Mistakes in Working with Metrics", ["data-culture"]),
    "cs-010": ("#056 — Is this a vanity metric?", ["vanity-metrics"]),
    "cs-011": ("#057 — Metrics Overlap", ["metric-maps", "diagnostics"]),
    "cs-012": ("#058 — 4 leverages of how to drive", ["frameworks", "diagnostics"]),
    "cs-013": ("#059 — 7 Analytics Myths and what to do instead", ["data-culture"]),
    "cs-014": ("#060 — 30 hypotheses for improving Average Items per Order", ["ecommerce-metrics", "diagnostics"]),
    "cs-015": ("#062 — Simpson's paradox explained", ["data-culture", "diagnostics"]),
    "cs-016": ("#063 — 4-Layer Dashboard Model", ["dashboards", "frameworks"]),
    "cs-017": ("#064 — The Hateful Ten", ["vanity-metrics"]),
    "cs-018": ("#065 — New Old way", ["data-culture"]),
    "cs-019": ("#066 — Dots and connections", ["metric-maps"]),
    "cs-020": ("#067 — 7 ways to decompose a key metric", ["metric-maps", "frameworks"]),
    "cs-021": ("#068 — Conversion ↑, Profit ↓", ["diagnostics", "ecommerce-metrics", "costs-profit"]),
    "cs-022": ("#069 — The Nothing Changed Problem", ["diagnostics"]),
    "cs-023": ("#070 — 3 dashboard types, 1 foundation", ["dashboards", "frameworks"]),
    "cs-024": ("#071 — Core map", ["metric-maps"]),
    "cs-025": ("#072 — Good vs Bad Dashboards", ["dashboards"]),
    "cs-026": ("#073 — Logic-first Dashboards Cascade", ["dashboards"]),
    "cs-027": ("#074 — 3 leverages of how to drive", ["frameworks", "diagnostics"]),
    "cs-028": ("#075 — How a Vanity Metric Becomes Useful", ["vanity-metrics"]),
    "cs-029": ("#076 — Your CEO doesn't care about your CTR", ["reporting", "vanity-metrics"]),
    "cs-030": ("#077 — 10 ways to slice your metrics", ["segmentation", "frameworks"]),
    "cs-031": ("#078 — The 4 layers of a Metrics System", ["frameworks", "dashboards"]),
    "cs-032": ("#079 — How Store's Costs Are Formed", ["costs-profit", "ecommerce-metrics"]),
    "cs-033": ("#080 — Reduce cart abandonment: Guide", ["ecommerce-metrics"]),
    "cs-034": ("#081 — How to structure dashboards the right way", ["dashboards"]),
    "cs-035": ("#082 — 9 Circles of E-commerce Analytics Hell", ["data-culture", "ecommerce-metrics"]),
    "cs-036": ("#083 — Metrics map ≠ metrics tree", ["metric-maps"]),
    "cs-037": ("#084 — SEO metrics map", ["seo", "metric-maps"]),
    "cs-038": ("#085 — 12 high-intent events behind your CR", ["ecommerce-metrics", "diagnostics"]),
    "cs-039": ("#087 — From definitions to focus", ["frameworks", "data-culture"]),
    "cs-040": ("#088 — E-commerce Growth Rules", ["ecommerce-metrics"]),
    "cs-041": ("#089 — With or without a metric map", ["metric-maps"]),
    "cs-042": ("#090 — The Lifecycle of Metric Maps and Trees", ["metric-maps"]),
    "cs-043": ("#091 — CRM metrics map", ["crm", "metric-maps"]),
    "cs-044": ("#092 — Analytics Priorities 2026", ["data-culture", "frameworks"]),
    "cs-045": ("#093 — 10-step AOV drop diagnostic algorithm", ["diagnostics", "ecommerce-metrics"]),
    "cs-046": ("#094 — Orders ↑, Profit ↓", ["diagnostics", "costs-profit", "ecommerce-metrics"]),
    "cs-047": ("#095 — 15 metric frameworks", ["frameworks"]),
    "cs-048": ("#096 — CR Driver Tree", ["metric-maps", "ecommerce-metrics"]),
    "cs-049": ("#097 — Spontaneous Decisions vs System", ["data-culture"]),
    "cs-050": ("#099 — How to define a key metric", ["frameworks"]),
    "cs-051": ("#100 — How to add a metric", ["frameworks", "dashboards"]),
    "cs-052": ("#103 — What people think 'checking why revenue dropped' looks like", ["diagnostics", "reporting"]),
    "cs-053": ("#105 — Metric went up — is that good?", ["diagnostics", "vanity-metrics"]),
    "cs-054": ("#106 — Same Revenue, different e-com apps", ["diagnostics", "ecommerce-metrics"]),
    "cs-055": ("#107 — How to explain metrics", ["reporting"]),
    "cs-056": ("#108 — Optimization is NOT Growth", ["data-culture", "ecommerce-metrics"]),
    "cs-057": ("#109 — One metric won't tell you what's wrong", ["diagnostics", "vanity-metrics"]),
    "cs-058": ("#112 — When growth is eating your e-commerce business", ["ecommerce-metrics", "costs-profit"]),
    "cs-059": ("#114 — How top e-commerce teams read their data differently", ["data-culture", "ecommerce-metrics"]),
    "cs-060": ("#117 — Symptoms of vanity metrics", ["vanity-metrics"]),
    "cs-061": ("#118 — How to cure vanity metrics", ["vanity-metrics"]),
    "cs-062": ("#121 — Types of metrics", ["frameworks"]),
    "cs-063": ("#122 — Types of relationships between metrics", ["frameworks", "metric-maps"]),
    "cs-064": ("#126 — Higher AOV might mean you're losing money", ["ecommerce-metrics", "diagnostics"]),
    "cs-065": ("#127 — Stop asking AI for answers", ["ai-analytics", "data-culture"]),
    "cs-066": ("#128 — How do we use Claude for our job (1/7)", ["ai-analytics"]),
    "cs-067": ("#128 — How do we use Claude for our job (2/7)", ["ai-analytics"]),
    "cs-068": ("#128 — How do we use Claude for our job (3/7)", ["ai-analytics"]),
    "cs-069": ("#128 — How do we use Claude for our job (4/7)", ["ai-analytics"]),
    "cs-070": ("#128 — How do we use Claude for our job (5/7)", ["ai-analytics"]),
    "cs-071": ("#128 — How do we use Claude for our job (6/7)", ["ai-analytics"]),
    "cs-072": ("#128 — How do we use Claude for our job (7/7)", ["ai-analytics"]),
    "cs-073": ("#129 — Read every metric drop through 5 questions", ["diagnostics", "frameworks"]),
    "cs-074": ("#135 — Decoration or Decision", ["dashboards", "data-culture"]),
    "cs-075": ("#136 — What your AI is missing", ["ai-analytics"]),
    "cs-076": ("#137 — When the Metric Becomes the Target", ["data-culture", "vanity-metrics"]),
    "cs-077": ("#138 — What your retention curve is actually telling you", ["retention", "diagnostics"]),
    "cs-078": ("14 types of underperforming products in e-commerce", ["ecommerce-metrics", "diagnostics"]),
    "cs-079": ("25 reasons reports aren't helping you grow", ["reporting", "dashboards"]),
    "cs-080": ("4 stages of retention decay", ["retention"]),
    "cs-081": ("#043 — You're optimizing the wrong repeat", ["retention", "ecommerce-metrics"]),
    "cs-082": ("5 типов взаимосвязей между метриками", ["frameworks", "metric-maps"]),
    "cs-083": ("7 способов измерить удержание в e-commerce", ["retention", "ecommerce-metrics"]),
    "cs-084": ("Beware of the Metric Trap", ["data-culture", "vanity-metrics"]),
    "cs-085": ("E-commerce Growth Flywheel", ["ecommerce-metrics", "frameworks"]),
    "cs-086": ("Hidden patterns from metric overlaps", ["metric-maps", "diagnostics"]),
    "cs-087": ("How to Analyze Seasonality", ["diagnostics", "ecommerce-metrics"]),
    "cs-088": ("Maze", ["data-culture"]),
    "cs-089": ("Tricky metrics that may mislead", ["vanity-metrics", "data-culture"]),
    "cs-090": ("What do you see in your dashboard?", ["dashboards"]),
    "cs-091": ("Как понять, почему метрика просела", ["diagnostics"]),
    "cs-092": ("Как скидки искажают ваши метрики", ["ecommerce-metrics", "diagnostics"]),
    "cs-093": ("Как убить data-driven культуру в компании", ["data-culture"]),
    "cs-094": ("Карты метрик против «плоских» дашбордов", ["metric-maps", "dashboards"]),
    "cs-095": ("Метрики, которые кажутся важными, но не ведут к решениям", ["vanity-metrics"]),
    "cs-096": ("Не доверяйте AOV вслепую", ["ecommerce-metrics", "diagnostics"]),
    "cs-097": ("Одинаковый LTV. Совершенно разные виды бизнеса", ["ecommerce-metrics", "diagnostics"]),
    "cs-098": ("Средние значения метрик не объясняют", ["diagnostics", "data-culture"]),
    "cs-099": ("Фокусируйтесь на рычагах, а не только на результатах", ["frameworks", "diagnostics"]),
    "cs-100": ("Что CR не объясняет", ["ecommerce-metrics", "diagnostics"]),
    "cs-101": ("Шахматная доска метрик в e-commerce", ["metric-maps", "ecommerce-metrics"]),
}

TAG_LABELS = {
    "dashboards": "Дашборды",
    "vanity-metrics": "Метрики-обманки",
    "metric-maps": "Карты и деревья метрик",
    "diagnostics": "Диагностика метрик",
    "ecommerce-metrics": "E-commerce метрики",
    "retention": "Удержание",
    "data-culture": "Data culture и ошибки",
    "frameworks": "Фреймворки и классификации",
    "seo": "SEO",
    "crm": "CRM",
    "ai-analytics": "AI и аналитика",
    "segmentation": "Сегментация",
    "costs-profit": "Расходы и прибыль",
    "reporting": "Отчётность и коммуникация",
}

with open("filename_map.json", encoding="utf-8") as f:
    filename_map = dict(json.load(f))

items = []
for cs_id, orig_filename in filename_map.items():
    title, tags = ENTRIES[cs_id]
    items.append({
        "id": cs_id,
        "title": title,
        "tags": tags,
        "pdf": f"pdf/{cs_id}.pdf",
        "thumb": f"thumbs/{cs_id}.png",
        "source": orig_filename,
    })

data = {
    "tags": TAG_LABELS,
    "items": items,
}

with open("data.json", "w", encoding="utf-8") as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print(f"Wrote {len(items)} items to data.json")
